CREATE TABLE IF NOT EXISTS inventory_items (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  max_stock INTEGER NOT NULL DEFAULT 10,
  visible BOOLEAN NOT NULL DEFAULT true,
  cost NUMERIC(10, 2) NOT NULL DEFAULT 0,
  item_type TEXT NOT NULL DEFAULT 'consumable'
);

INSERT INTO inventory_items (name, description, category, stock, max_stock, visible, cost, item_type) VALUES
  ('All-Purpose Cleaner', 'Multi-surface cleaning spray for counters, sinks, and appliances', 'Sprays', 8, 10, true, 3.99, 'consumable'),
  ('Glass Cleaner', 'Streak-free window and mirror cleaning solution', 'Sprays', 6, 10, true, 4.49, 'consumable'),
  ('Disinfectant Spray', 'Hospital-grade disinfectant for bathrooms and high-touch areas', 'Sprays', 5, 10, true, 5.99, 'consumable'),
  ('Microfiber Cloths', 'Reusable lint-free cloths for dusting and polishing', 'Cloths & Wipes', 12, 20, true, 1.50, 'cleaning'),
  ('Sponges', 'Heavy-duty scrub sponges for kitchen and bathroom cleaning', 'Cloths & Wipes', 10, 15, true, 0.99, 'consumable'),
  ('Trash Bags', 'Large 13-gallon drawstring trash bags', 'Supplies', 20, 30, true, 0.25, 'consumable'),
  ('Toilet Bowl Cleaner', 'Deep cleaning gel for toilet bowls and rims', 'Bathroom', 4, 10, true, 3.49, 'consumable'),
  ('Floor Cleaner', 'Concentrated multi-floor mopping solution', 'Floors', 3, 8, true, 6.99, 'consumable'),
  ('Dusting Spray', 'Furniture polish and dusting spray', 'Sprays', 7, 10, true, 4.29, 'consumable'),
  ('Rubber Gloves', 'Disposable nitrile gloves for hygiene protection', 'Supplies', 15, 25, true, 0.50, 'cleaning'),
  ('Mop Heads', 'Replacement mop heads for wet mopping', 'Floors', 2, 6, true, 8.99, 'cleaning'),
  ('Vacuum Bags', 'Replacement bags for commercial vacuum cleaners', 'Supplies', 5, 10, true, 2.99, 'cleaning'),
  ('Water Bottles', 'Bottled water for cleaning staff', 'Supplies', 10, 10, true, 0.50, 'consumable'),
  ('Wash Cloths', 'Reusable wash cloths for cleaning', 'Cloths & Wipes', 10, 10, true, 1.00, 'cleaning'),
  ('Paper Towels', 'Disposable paper towels', 'Supplies', 10, 10, true, 2.00, 'consumable'),
  ('Salt', 'Salt shaker refill', 'Supplies', 10, 10, true, 1.00, 'consumable'),
  ('Pepper', 'Pepper shaker refill', 'Supplies', 10, 10, true, 1.00, 'consumable'),
  ('Diffuser Oil', 'Essential oil for diffusers', 'Supplies', 10, 10, true, 5.00, 'consumable'),
  ('Bleach', 'Bleach cleaning solution', 'Bathroom', 10, 10, true, 3.00, 'consumable'),
  ('Dish Soap Re-fill', 'Large refill bottle for dish soap', 'Supplies', 10, 10, true, 4.00, 'consumable'),
  ('Mini Dish Soap', 'Small travel-size dish soap', 'Supplies', 10, 10, true, 1.50, 'consumable'),
  ('Broom', 'Standard cleaning broom', 'Floors', 5, 5, true, 8.00, 'cleaning'),
  ('Mop', 'Floor mop for cleaning', 'Floors', 5, 5, true, 10.00, 'cleaning'),
  ('Dust Pan', 'Dust pan for sweeping', 'Floors', 5, 5, true, 3.00, 'cleaning'),
  ('Mop Bucket', 'Bucket for mopping', 'Floors', 3, 3, true, 12.00, 'cleaning'),
  ('Glass Cook Top', 'Glass cooktop cleaner', 'Sprays', 10, 10, true, 5.00, 'consumable'),
  ('Scorch Pad', 'Scouring pad for tough stains', 'Cloths & Wipes', 10, 10, true, 1.50, 'consumable'),
  ('Hand Soap Refill', 'Large refill bottle for hand soap', 'Bathroom', 10, 10, true, 3.50, 'consumable'),
  ('Coffee Packs', 'Single serve coffee packs', 'Supplies', 10, 10, true, 6.00, 'consumable'),
  ('Bathroom Trash Bags', 'Small trash bags for bathroom bins', 'Supplies', 10, 10, true, 2.00, 'consumable'),
  ('Scrub Brushes', 'Cleaning scrub brushes', 'Cloths & Wipes', 10, 10, true, 2.50, 'cleaning'),
  ('Masks', 'Disposable face masks', 'Supplies', 20, 20, true, 0.50, 'consumable'),
  ('Spray Bottle', 'Empty spray bottle with trigger', 'Supplies', 10, 10, true, 2.00, 'cleaning'),
  ('Shampoo', 'Shampoo for guest bathrooms', 'Bathroom', 10, 10, true, 4.00, 'consumable'),
  ('Body Soap', 'Liquid body wash', 'Bathroom', 10, 10, true, 4.00, 'consumable'),
  ('Body Bar Soap', 'Bar soap for bathrooms', 'Bathroom', 10, 10, true, 1.50, 'consumable'),
  ('Lotion', 'Body lotion for guest amenities', 'Bathroom', 10, 10, true, 3.50, 'consumable'),
  ('Conditioner', 'Hair conditioner for guest bathrooms', 'Bathroom', 10, 10, true, 4.00, 'consumable'),
  ('Laundry Soap', 'Liquid laundry detergent', 'Supplies', 10, 10, true, 8.00, 'consumable')
ON CONFLICT (name) DO NOTHING;
